version: '3.8'

services:
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      - app-data:/app/data
    networks:
      - app-network
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: postgres
    ports:
      - "49153:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  app-data:
  db-data: 

networks:
  app-network: